columns:
  - having_IP_Address: int64
  - URL_Length: int64
  - Shortining_Service: int64
  - having_At_Symbol: int64
  - double_slash_redirecting: int64
  - Prefix_Suffix: int64
  - having_Sub_Domain: int64
  - SSLfinal_State: int64
  - Domain_registeration_length: int64
  - Favicon: int64
  - port: int64
  - HTTPS_token: int64
  - Request_URL: int64
  - URL_of_Anchor: int64
  - Links_in_tags: int64
  - SFH: int64
  - Submitting_to_email: int64
  - Abnormal_URL: int64
  - Redirect: int64
  - on_mouseover: int64
  - RightClick: int64
  - popUpWidnow: int64
  - Iframe: int64
  - age_of_domain: int64
  - DNSRecord: int64
  - web_traffic: int64
  - Page_Rank: float64
  - Google_Index: int64
  - Links_pointing_to_page: int64
  - Statistical_report: int64
  - Result: int64

numerical_columns_dtypes:
  having_IP_Address: int
  URL_Length: int
  Shortining_Service: int
  having_At_Symbol: int
  double_slash_redirecting: int
  Prefix_Suffix: int
  having_Sub_Domain: int
  SSLfinal_State: int
  Domain_registeration_length: int
  Favicon: int
  port: int
  HTTPS_token: int
  Request_URL: int
  URL_of_Anchor: int
  Links_in_tags: int
  SFH: int
  Submitting_to_email: int
  Abnormal_URL: int
  Redirect: int
  on_mouseover: int
  RightClick: int
  popUpWidnow: int
  Iframe: int
  age_of_domain: int
  DNSRecord: int
  web_traffic: int
  Page_Rank: float
  Google_Index: int
  Links_pointing_to_page: int
  Statistical_report: int
  Result: int